name: .NET Integration Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  integration-tests:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Install Azure Functions Core Tools
      run: |
        # Import the Microsoft GPG key
        curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
        sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
        
        # Add the Microsoft package feed
        sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
        
        # Install the tools
        sudo apt-get update
        sudo apt-get install azure-functions-core-tools-4
      
    - name: Prepare Test Environment
      env:
        "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated"
      run: |
        docker compose up -d --wait
        func start --script-root ./AzureFunctionApp --no-build &
        sleep 15 # Wait for the function app to start

    - name: Test
      run: dotnet test --filter TestCategory=Integration --no-restore --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: TestResults
        path: ./TradeBot.IntegrationTests/TestResults/TestResults.trx